name: generate-snake-game-from-github-contribution-grid

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight
  workflow_dispatch:        # lets you run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: vivekgotstack
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=2572c5&color_snake_body=0b1d3a&color_snake_head=60a5fa&color_dots=#0a0a0a,#052e16,#14532d,#22c55e,#4ade80&background=000000&shadow=true
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=2572c5&color_snake_body=0b1d3a&color_snake_head=60a5fa&color_dots=#0a0a0a,#052e16,#14532d,#22c55e,#4ade80&background=000000&shadow=true

      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
